package modelo.contenido;

public enum Genero {
	ACCION, ARCADE, AVENTURAS, BELICO, CASUAL, CIENCIA_FICCION, COMEDIA, CRIMEN, DEPORTIVO, DOCUMENTAL, DRAMA, ECCHI, EDUCATIVO, ESCOLARES, ESPACIAL, FANTASIA, GORE, HISTORIA, INDIE, INFANTIL, MULTIJUGADOR, MUNDO_ABIERTO, MUSICAL, PARANORMAL, POLICIACA, PSICOLOGICO, REALIDAD, ROMANCE, RPG, RV, SEINEN, SHONEN, SHOUJO, SUPERHEROES, SUSPENSE, TERROR, WESTERN
}
